Repository Dlux804/McQuade-Chem-ML, pull requests merged in 2020-08, with the labels that each got.

#78 Hot fix neo4j files
  core/analysis.py
  core/features.py
  core/models.py
  core/neo4j/fragments.py
  core/neo4j/nodes_to_neo4j.py
  core/neo4j/rel_to_neo4j.py
  main.py
Labels: bug, enhancement

#76 Main.py cleanup, storage for classification workflow, graphical evaluation for single-label classification
  .idea/dictionaries/User.xml
  .idea/dictionaries/user.xml
  core/Get_Classification.py
  core/Get_Task_Type.py
  core/analysis.py
  core/classifiers.py
  core/features.py
  core/grid.py
  core/models.py
  core/name.py
  core/regressors.py
  core/train.py
  main.py
Labels: enhancement

#79 Neo4j dev
  core/features.py
  core/models.py
  core/neo4j/fragments.py
  core/neo4j/make_query.py
  core/neo4j/nodes_to_neo4j.py
  core/neo4j/output_to_neo4j.py
  core/neo4j/prep_from_outputs.py
  core/neo4j/rel_to_neo4j.py
  core/storage/dictionary.py
  main.py
  tests/test_regressors.py
Labels: bug, enhancement

#81 Hot fix neo4j bug
  core/grid.py
  core/neo4j/fragments.py
  core/neo4j/nodes_to_neo4j.py
  core/neo4j/rel_to_neo4j.py
  core/regressors.py
  main.py
Labels: bug

#86 Fix ontology and fix bug
  .circleci/config.yml
  core/features.py
  core/neo4j/make_query.py
  core/neo4j/nodes_to_neo4j.py
  core/neo4j/rel_to_neo4j.py
  core/train.py
  main.py
  new_tests/test_analysis.py
  new_tests/test_features.py
  new_tests/test_grid.py
  new_tests/test_ingest.py
  new_tests/test_keras.py
  new_tests/test_regressors.py
  new_tests/test_storage.py
  new_tests/test_train.py
  tests/model_fixture.py
  tests/test_analysis.py
  tests/test_grid.py
  tests/test_keras.py
  tests/test_sklearn.py
  tests/test_storage.py
  tests/test_train.py
Labels: bug, enhancement
