Repository Dlux804/McQuade-Chem-ML, pull requests merged in 2020-09, with the labels that each got.

#87 Development andres
  .idea/dictionaries/user.xml
  .idea/sqldialects.xml
  Qsar_examples/2000JCICS1337.zip
  Qsar_examples/2009QCS790.qdb.zip
  Qsar_examples/2011JCC2386.qdb.zip
  Qsar_examples/2012JHM169.qdb.zip
  Qsar_examples/2014JCC1036.qdb.zip
  Qsar_examples/2014JLPPI1.qdb.zip
  Qsar_examples/2017MI1700024.qdb.zip
  Qsar_examples/Q13-26-0009.qdb.zip
  Qsar_examples/Q13-31-0060.qdb.zip
  core/__init__.py
  core/analysis.py
  core/features.py
  core/grid.py
  core/ingest.py
  core/models.py
  core/neo4j/__init__.py
  core/neo4j/fragments.py
  core/neo4j/make_query.py
  core/neo4j/models_to_neo4j.py
  core/neo4j/nodes_to_neo4j.py
  core/neo4j/output_to_neo4j.py
  core/neo4j/prep_from_outputs.py
  core/neo4j/rel_to_neo4j.py
  core/regressors.py
  core/storage/__init__.py
  core/storage/dictionary.py
  core/storage/mysql.py
  core/storage/qsar_export.py
  core/storage/qsar_to_neo4j.py
  core/train.py
  main.py
  water-energy-rf-2-tuned/.idea/water-energy-rf-2-tuned.iml
Labels: bug, enhancement, optimization

#89 Q dev
  .idea/dictionaries/user.xml
  core/analysis.py
  core/models.py
  core/neo4j/models_to_neo4j.py
  core/regressors.py
  core/storage/__init__.py
  core/storage/misc.py
  dataFiles/testdata/Lipo-short.csv
  main.py
  tests/model_fixture.py
  tests/test_keras.py
Labels: bug, enhancement

#91 Q dev
  core/features.py
  core/grid.py
  core/models.py
  core/name.py
  core/neo4j/models_to_neo4j.py
  core/regressors.py
  core/storage/dictionary.py
  core/storage/util.py
  main.py
  tests/test_storage.py
Labels: bug, enhancement

#85 Added new sklearn models and hyper-paremeter tuning for classification workflow.
  core/Get_Task_Type.py
  core/analysis.py
  core/classifiers.py
  core/models.py
  core/neo4j/models_to_neo4j.py
  core/regressors.py
  core/train.py
  main.py
Labels: enhancement
