Repository Dlux804/McQuade-Chem-ML, pull requests merged in 2020-01, with the labels that each got.

#19 Organize
  .circleci/config.yml
  .gitignore
  README.md
  core/grid.py
  core/models.py
  examples_scripts/barzilay_predict_example.py
  examples_scripts/descriptastorus-example.py
  graphics/hte-models-overview
  graphics/hte-models-overview.drawio
  graphics/hte-models-overview.png
  graphics/hte-models-overview.svg
  main.py
  output/.gitignore
  test_test.py
  tests/test_features.py
  tests/test_ingest.py
  toc.sh
Labels: documentation

#22 Testing
  .circleci/config.yml
  core/analysis.py
  core/features.py
  core/models.py
  env_init/mlapp.yml
  tests/test_analysis.py
  tests/test_features.py
  tests/test_ingest.py
  tests/test_misc.py
  tests/test_models.py
  tests/test_regressors.py
Labels: Stability, question

#24 Fix analysis
  core/analysis.py
  core/grid.py
  core/models.py
  main.py
Labels: Stability

#25 Added doc strings and comments throughout core/files.
  core/features.py
  core/grid.py
  core/misc.py
  core/models.py
  core/regressors.py
  main.py
Labels: documentation
