Repository Dlux804/McQuade-Chem-ML, pull requests merged in 2020-06, with the labels that each got.

#47 Feature q
  core/analysis.py
  core/features.py
  core/grid.py
  core/models.py
  core/name.py
  core/regressors.py
  env_init/mlapp.yml
  main.py
  tests/test_models.py
  tests/test_regressors.py
Labels: documentation, enhancement, optimization

#48 Added sklearn classification pipeline to main workflow.
  core/analysis.py
  core/classifiers.py
  core/features.py
  core/ingest.py
  core/models.py
  core/name.py
  dataFiles/sider.csv
  main.py
Labels: enhancement

#52 Code refactorization to use model class instance ubiquitously
  core/analysis.py
  core/classifiers.py
  core/compare.py
  core/enrich.py
  core/features.py
  core/grid.py
  core/ingest.py
  core/misc.py
  core/models.py
  core/name.py
  core/regressors.py
  core/storage.py
  core/train.py
  main.py
  tests/test_analysis.py
  tests/test_features.py
  tests/test_regressors.py
Labels: Stability, optimization
